export const productosData = {
  "prod_1": { "codigo": "3D-001", "nombre": "Llavero 3D Personalizado", "descripcion": "Llavero impreso en PLA de alta resistencia.", "precio": 2500, "categoria": "3d", "urlImagen": "" },
  "prod_2": { "codigo": "3D-002", "nombre": "Figura Estatua Anime (Goku / Luffy)", "descripcion": "Estatua coleccionable detallada, altura 18cm.", "precio": 18000, "categoria": "3d", "urlImagen": "" },
  "prod_3": { "codigo": "3D-003", "nombre": "Soporte para Audífonos 3D", "descripcion": "Diseño ergonómico y resistente.", "precio": 8500, "categoria": "3d", "urlImagen": "" },
  "prod_4": { "codigo": "3D-004", "nombre": "Macetero Geométrico de Polímero", "descripcion": "Macetero decorativo con sistema de drenaje.", "precio": 6000, "categoria": "3d", "urlImagen": "" },
  "prod_5": { "codigo": "3D-005", "nombre": "Organizador de Cables para Escritorio", "descripcion": "Fijador modular para mantener el orden.", "precio": 4000, "categoria": "3d", "urlImagen": "" },
  "prod_6": { "codigo": "3D-006", "nombre": "Cortador de Galletas Temático", "descripcion": "Molde para repostería apto para contacto alimenticio.", "precio": 3000, "categoria": "3d", "urlImagen": "" },
  "prod_7": { "codigo": "3D-007", "nombre": "Soporte para Celular y Control", "descripcion": "Base ajustable para smartphones y mandos.", "precio": 5000, "categoria": "3d", "urlImagen": "" },
  "prod_8": { "codigo": "3D-008", "nombre": "Lithophane (Lámpara con Foto Grabada)", "descripcion": "Revela una fotografía al encender luz trasera.", "precio": 14000, "categoria": "3d", "urlImagen": "" },
  "prod_9": { "codigo": "3D-009", "nombre": "Posavasos Hexagonales (Pack de 4)", "descripcion": "Diseño moderno con base antideslizante.", "precio": 4500, "categoria": "3d", "urlImagen": "" },
  "prod_10": { "codigo": "3D-010", "nombre": "Articulado Dragón Mágico", "descripcion": "Figura articulada de fantasía en una pieza.", "precio": 12000, "categoria": "3d", "urlImagen": "" },
  "prod_11": { "codigo": "TECH-001", "nombre": "Disco Duro Externo 1TB", "descripcion": "Almacenamiento portátil USB 3.0 de alta velocidad.", "precio": 45000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_12": { "codigo": "TECH-002", "nombre": "Memoria RAM 8GB DDR4", "descripcion": "Módulo de memoria para PC de escritorio.", "precio": 28000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_13": { "codigo": "TECH-003", "nombre": "Batería Externa Powerbank 10000mAh", "descripcion": "Carga rápida con doble salida USB.", "precio": 15000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_14": { "codigo": "TECH-004", "nombre": "Cable Tipo C Mallado 1M", "descripcion": "Cable reforzado de alta durabilidad.", "precio": 4000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_15": { "codigo": "TECH-005", "nombre": "Audífonos Bluetooth Deportivos", "descripcion": "Con cancelación de ruido y estuche.", "precio": 12000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_16": { "codigo": "TECH-006", "nombre": "Disco Duro SSD 480GB", "descripcion": "Estado sólido ultrarrápido.", "precio": 32000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_17": { "codigo": "TECH-007", "nombre": "Hub USB 3.0 de 4 Puertos", "descripcion": "Expansor multidispositivo con LED.", "precio": 7500, "categoria": "tecnologia", "urlImagen": "" },
  "prod_18": { "codigo": "TECH-008", "nombre": "Mouse Inalámbrico Ergonómico", "descripcion": "Diseño silencioso 2.4GHz.", "precio": 8000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_19": { "codigo": "TECH-009", "nombre": "Teclado Mecánico Compacto RGB", "descripcion": "Switches táctiles y retroiluminación.", "precio": 29000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_20": { "codigo": "TECH-010", "nombre": "Tarjeta MicroSD 64GB Clase 10", "descripcion": "Incluye adaptador SD.", "precio": 9000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_21": { "codigo": "TECH-011", "nombre": "Cargador de Pared USB-C 20W", "descripcion": "Carga rápida.", "precio": 8500, "categoria": "tecnologia", "urlImagen": "" },
  "prod_22": { "codigo": "TECH-012", "nombre": "Adaptador HDMI a VGA", "descripcion": "Conexión para equipos clásicos.", "precio": 5500, "categoria": "tecnologia", "urlImagen": "" },
  "prod_23": { "codigo": "TECH-013", "nombre": "Parlante Bluetooth Portátil", "descripcion": "Resistente a salpicaduras.", "precio": 16000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_24": { "codigo": "TECH-014", "nombre": "Cooler Base para Notebook", "descripcion": "Ventiladores silenciosos con LED.", "precio": 13500, "categoria": "tecnologia", "urlImagen": "" },
  "prod_25": { "codigo": "TECH-015", "nombre": "Memoria USB Pendrive 32GB", "descripcion": "Carcasa metálica USB 3.1.", "precio": 6500, "categoria": "tecnologia", "urlImagen": "" },
  "prod_26": { "codigo": "TECH-016", "nombre": "Luz LED para Monitor (Barra)", "descripcion": "Iluminación ajustable.", "precio": 19000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_27": { "codigo": "TECH-017", "nombre": "Cable HDMI 2.0 mallado 2M", "descripcion": "Resolución 4K a 60Hz.", "precio": 5000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_28": { "codigo": "TECH-018", "nombre": "Cámara Web HD 1080p", "descripcion": "Ideal para streaming y videollamadas.", "precio": 21000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_29": { "codigo": "TECH-019", "nombre": "Soporte de Celular para Auto", "descripcion": "Fijación firme a ventilación.", "precio": 6000, "categoria": "tecnologia", "urlImagen": "" },
  "prod_30": { "codigo": "TECH-020", "nombre": "Disipador para SSD M.2 NVMe", "descripcion": "Disipador de aluminio con thermal pads.", "precio": 4500, "categoria": "tecnologia", "urlImagen": "" }
};